// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWith(arg1) {
  return window['go']['terminal']['Terminal']['ConnectWith'](arg1);
}

export function Disconnect() {
  return window['go']['terminal']['Terminal']['Disconnect']();
}

export function Resize(arg1, arg2) {
  return window['go']['terminal']['Terminal']['Resize'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['terminal']['Terminal']['Send'](arg1);
}

export function Startup(arg1) {
  return window['go']['terminal']['Terminal']['Startup'](arg1);
}
