// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {context} from '../models';

export function Login(arg1:handlers.LoginInput):Promise<handlers.LoginResponse>;

export function Logout(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
