// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1) {
  return window['go']['handlers']['AuthHandlerStruct']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['handlers']['AuthHandlerStruct']['Logout'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['AuthHandlerStruct']['Startup'](arg1);
}
