// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {container} from '../models';
import {network} from '../models';
import {volume} from '../models';
import {image} from '../models';
import {context} from '../models';

export function AddDockerClient(arg1:number):Promise<void>;

export function CatchClient(arg1:number):Promise<client.Client>;

export function ConnectDocker(arg1:number):Promise<void>;

export function ContainerInspect(arg1:number,arg2:string):Promise<string>;

export function ContainerLogs(arg1:number,arg2:string):Promise<string>;

export function ContainerPause(arg1:number,arg2:string):Promise<void>;

export function ContainerRemove(arg1:number,arg2:string):Promise<void>;

export function ContainerRename(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ContainerRestart(arg1:number,arg2:string):Promise<void>;

export function ContainerUnPause(arg1:number,arg2:string):Promise<void>;

export function ContainersList(arg1:number):Promise<Array<container.Summary>>;

export function CreateNetwork(arg1:number,arg2:string,arg3:network.CreateOptions):Promise<string>;

export function CreateVolume(arg1:number,arg2:volume.CreateOptions):Promise<string>;

export function DeleteNetwork(arg1:number,arg2:string):Promise<void>;

export function DeleteVolume(arg1:number,arg2:string):Promise<void>;

export function ImagesList(arg1:number):Promise<Array<image.Summary>>;

export function InspectImage(arg1:number,arg2:string):Promise<string>;

export function InspectNetwork(arg1:number,arg2:string):Promise<string>;

export function InspectVolume(arg1:number,arg2:string):Promise<string>;

export function ListNetworks(arg1:number):Promise<string>;

export function ListVolumes(arg1:number):Promise<string>;

export function PruneImages(arg1:number):Promise<image.PruneReport>;

export function PruneNetworks(arg1:number):Promise<string>;

export function RemoveImage(arg1:number,arg2:string):Promise<Array<image.DeleteResponse>>;

export function StartContainerStats(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopContainerStats(arg1:number,arg2:string):Promise<void>;

export function StreamStats(arg1:client.Client,arg2:context.Context,arg3:string,arg4:context.Context):Promise<void>;
