// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerInspect(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerInspect'](arg1);
}

export function ContainerLogs(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerLogs'](arg1);
}

export function ContainerPause(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerPause'](arg1);
}

export function ContainerRemove(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerRemove'](arg1);
}

export function ContainerRename(arg1, arg2) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerRename'](arg1, arg2);
}

export function ContainerRestart(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerRestart'](arg1);
}

export function ContainerUnPause(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainerUnPause'](arg1);
}

export function ContainersList() {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ContainersList']();
}

export function ImagesList() {
  return window['go']['handlers']['DockerSdkHandlerStruct']['ImagesList']();
}

export function InspectImage(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['InspectImage'](arg1);
}

export function PruneImages() {
  return window['go']['handlers']['DockerSdkHandlerStruct']['PruneImages']();
}

export function RemoveImage(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['RemoveImage'](arg1);
}

export function StartContainerStats(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['StartContainerStats'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['Startup'](arg1);
}

export function StopContainerStats(arg1) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['StopContainerStats'](arg1);
}

export function StreamStats(arg1, arg2) {
  return window['go']['handlers']['DockerSdkHandlerStruct']['StreamStats'](arg1, arg2);
}
