// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDockerCredential(arg1, arg2) {
  return window['go']['handlers']['DockerHandlerStruct']['ConnectDockerCredential'](arg1, arg2);
}

export function CreateDockerConnection(arg1, arg2) {
  return window['go']['handlers']['DockerHandlerStruct']['CreateDockerConnection'](arg1, arg2);
}

export function FindAllByUser(arg1, arg2) {
  return window['go']['handlers']['DockerHandlerStruct']['FindAllByUser'](arg1, arg2);
}

export function GetDockerConnectionById(arg1, arg2) {
  return window['go']['handlers']['DockerHandlerStruct']['GetDockerConnectionById'](arg1, arg2);
}

export function GetDockerConnectionByIdWithoutToken(arg1) {
  return window['go']['handlers']['DockerHandlerStruct']['GetDockerConnectionByIdWithoutToken'](arg1);
}

export function RegisterDockerSdkHandler(arg1) {
  return window['go']['handlers']['DockerHandlerStruct']['RegisterDockerSdkHandler'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['DockerHandlerStruct']['Startup'](arg1);
}
