// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {models} from '../models';
import {handlers} from '../models';
import {context} from '../models';

export function ConnectDockerCredential(arg1:string,arg2:number):Promise<void>;

export function CreateDockerConnection(arg1:string,arg2:dtos.CreateDockerConnectionDto):Promise<void>;

export function FindAllByUser(arg1:string,arg2:number):Promise<Array<models.DockerCredentialsModel>>;

export function GetDockerConnectionById(arg1:string,arg2:number):Promise<models.DockerCredentialsModel>;

export function GetDockerConnectionByIdWithoutToken(arg1:number):Promise<models.DockerCredentialsModel>;

export function RegisterDockerSdkHandler(arg1:handlers.DockerSdkHandlerStruct):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
