// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {context} from '../models';

export function CreateSshConnection(arg1:dtos.CreateSshConnectionInput):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
