// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {context} from '../models';

export function CreateSshConnection(arg1:string,arg2:dtos.CreateSshConnectionInputDto):Promise<void>;

export function DeleteConnection(arg1:string,arg2:number):Promise<void>;

export function FindAllConnectionByUser(arg1:string,arg2:number):Promise<Array<dtos.SshDto>>;

export function GetById(arg1:string,arg2:number):Promise<dtos.SshDto>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSshConnection(arg1:string,arg2:number,arg3:dtos.CreateSshConnectionInputDto):Promise<void>;
