// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSshConnection(arg1) {
  return window['go']['handlers']['SshHandler']['CreateSshConnection'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['SshHandler']['Startup'](arg1);
}
