// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSshConnection(arg1, arg2) {
  return window['go']['handlers']['SshHandlerStruct']['CreateSshConnection'](arg1, arg2);
}

export function DeleteConnection(arg1, arg2) {
  return window['go']['handlers']['SshHandlerStruct']['DeleteConnection'](arg1, arg2);
}

export function FindAllConnectionByUser(arg1, arg2) {
  return window['go']['handlers']['SshHandlerStruct']['FindAllConnectionByUser'](arg1, arg2);
}

export function GetById(arg1, arg2) {
  return window['go']['handlers']['SshHandlerStruct']['GetById'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['handlers']['SshHandlerStruct']['Startup'](arg1);
}

export function UpdateSshConnection(arg1, arg2, arg3) {
  return window['go']['handlers']['SshHandlerStruct']['UpdateSshConnection'](arg1, arg2, arg3);
}
