// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWith(arg1) {
  return window['go']['handlers']['TerminalHandlerStruct']['ConnectWith'](arg1);
}

export function Disconnect() {
  return window['go']['handlers']['TerminalHandlerStruct']['Disconnect']();
}

export function Resize(arg1, arg2) {
  return window['go']['handlers']['TerminalHandlerStruct']['Resize'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['handlers']['TerminalHandlerStruct']['Send'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['TerminalHandlerStruct']['Startup'](arg1);
}
