// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['handlers']['UserHandler']['Create'](arg1);
}

export function GetByID(arg1, arg2) {
  return window['go']['handlers']['UserHandler']['GetByID'](arg1, arg2);
}

export function MyInfo(arg1) {
  return window['go']['handlers']['UserHandler']['MyInfo'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['UserHandler']['Startup'](arg1);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['handlers']['UserHandler']['Update'](arg1, arg2, arg3);
}
