// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';
import {context} from '../models';

export function Create(arg1:dtos.CreateUserInput):Promise<dtos.UserDTO>;

export function GetByID(arg1:string,arg2:number):Promise<dtos.UserDTO>;

export function Me(arg1:string):Promise<dtos.UserDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:number,arg3:dtos.UpdateUserInput):Promise<dtos.UserDTO>;
