// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainersList() {
  return window['go']['docker']['Docker']['ContainersList']();
}

export function Startup(arg1) {
  return window['go']['docker']['Docker']['Startup'](arg1);
}
