// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {image} from '../models';
import {context} from '../models';

export function ContainerInspect(arg1:string):Promise<string>;

export function ContainerLogs(arg1:string):Promise<string>;

export function ContainerPause(arg1:string):Promise<void>;

export function ContainerRemove(arg1:string):Promise<void>;

export function ContainerRename(arg1:string,arg2:string):Promise<void>;

export function ContainerRestart(arg1:string):Promise<void>;

export function ContainerUnPause(arg1:string):Promise<void>;

export function ContainersList():Promise<Array<container.Summary>>;

export function ImagesList():Promise<Array<image.Summary>>;

export function InspectImage(arg1:string):Promise<string>;

export function PruneImages():Promise<image.PruneReport>;

export function RemoveImage(arg1:string):Promise<Array<image.DeleteResponse>>;

export function StartContainerStats(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopContainerStats(arg1:string):Promise<void>;

export function StreamStats(arg1:context.Context,arg2:string):Promise<void>;
