// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerInspect(arg1) {
  return window['go']['docker']['Docker']['ContainerInspect'](arg1);
}

export function ContainerLogs(arg1) {
  return window['go']['docker']['Docker']['ContainerLogs'](arg1);
}

export function ContainerPause(arg1) {
  return window['go']['docker']['Docker']['ContainerPause'](arg1);
}

export function ContainerRemove(arg1) {
  return window['go']['docker']['Docker']['ContainerRemove'](arg1);
}

export function ContainerRename(arg1, arg2) {
  return window['go']['docker']['Docker']['ContainerRename'](arg1, arg2);
}

export function ContainerRestart(arg1) {
  return window['go']['docker']['Docker']['ContainerRestart'](arg1);
}

export function ContainerUnPause(arg1) {
  return window['go']['docker']['Docker']['ContainerUnPause'](arg1);
}

export function ContainersList() {
  return window['go']['docker']['Docker']['ContainersList']();
}

export function ImagesList() {
  return window['go']['docker']['Docker']['ImagesList']();
}

export function InspectImage(arg1) {
  return window['go']['docker']['Docker']['InspectImage'](arg1);
}

export function PruneImages() {
  return window['go']['docker']['Docker']['PruneImages']();
}

export function RemoveImage(arg1) {
  return window['go']['docker']['Docker']['RemoveImage'](arg1);
}

export function StartContainerStats(arg1) {
  return window['go']['docker']['Docker']['StartContainerStats'](arg1);
}

export function Startup(arg1) {
  return window['go']['docker']['Docker']['Startup'](arg1);
}

export function StopContainerStats(arg1) {
  return window['go']['docker']['Docker']['StopContainerStats'](arg1);
}

export function StreamStats(arg1, arg2) {
  return window['go']['docker']['Docker']['StreamStats'](arg1, arg2);
}
