// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {context} from '../models';

export function ContainersList():Promise<Array<container.Summary>>;

export function Startup(arg1:context.Context):Promise<void>;
